"""empty message

Revision ID: 4022b16b80d0
Revises: 0b407d0cf82a
Create Date: 2025-07-23 17:59:43.721373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4022b16b80d0'
down_revision = '0b407d0cf82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
